[package]
name = "auto_array"
version = "0.1.1"
edition = "2021"
rust-version = "1.56.0" # MSRV

license = "MIT OR Apache-2.0"
repository = "https://github.com/lars-schumann/auto_array"
# homepage = ""
readme = "README.md"
description = "A macro to automatically calculate the length of arrays"
keywords = ["auto", "array", "const", "macro"]


[dependencies]
